#############################################################################
# Makefile for building: zkCar
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? 4? 10 11:13:33 2019
# Project:  zkCar.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile zkCar.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT_LIB -DQT_SCRIPT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtScript -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -I../../doc/wen_doc/Hi3531A_SDK_V1.0.4.0/mpp/extdrv/tlv320aic31 -I../../doc/wen_doc/Hi3531A_SDK_V1.0.4.0/mpp/include -Ilib/faac/include -Ilib/mp4v2/include -Ilib/faad/include -Ilib/mp4v2/include -Ilib/libcurl/include -Ilib/zlib/include -Ilib/openssl/include -Ilib/openssl/include -Ilib/faac/include -I. -IUI
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/home/tys/software/zkCar/lib/ -lzkpush -lzkrtsp -L/home/tys/software/zkCar/../../doc/wen_doc/Hi3531A_SDK_V1.0.4.0/mpp/lib/ -lmpi -lhdmi -ljpeg -lupvqe -ldnvqe -lVoiceEngine -L/home/tys/software/zkCar/lib/faac/lib/ -L/home/tys/software/zkCar/lib/faad/lib/ -lfaad -L/home/tys/software/zkCar/lib/mp4v2/lib/ -lmp4v2 -L/home/tys/software/zkCar/lib/libcurl/lib/ -lcurl -lhisicar -L/home/tys/software/zkCar/lib/zlib/lib/ -lz -L/home/tys/software/zkCar/lib/openssl/lib/ -lssl -lcrypto -lfaac -lQtWebKit -lQtScript -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwidget.cpp \
		onescreen.cpp \
		fourscreen.cpp \
		button_localvedio_listwidget.cpp \
		localVedioMenu.cpp \
		screenModeMenu.cpp \
		pushButtonMenu.cpp \
		twoScreen.cpp \
		nineScreen.cpp \
		sixteenScreen.cpp \
		electronicMap.cpp \
		interactionManager.cpp \
		vedioMeeting.cpp \
		vedioSearch.cpp \
		dateTimeButton.cpp \
		date.cpp \
		mediaplayer.cpp moc_mainwidget.cpp \
		moc_onescreen.cpp \
		moc_fourscreen.cpp \
		moc_button_localvedio_listwidget.cpp \
		moc_localVedioMenu.cpp \
		moc_screenModeMenu.cpp \
		moc_twoScreen.cpp \
		moc_nineScreen.cpp \
		moc_sixteenScreen.cpp \
		moc_electronicMap.cpp \
		moc_interactionManager.cpp \
		moc_vedioMeeting.cpp \
		moc_vedioSearch.cpp \
		moc_dateTimeButton.cpp \
		moc_date.cpp \
		moc_mediaplayer.cpp \
		qrc_statuslog.cpp \
		qrc_datetimeimg.cpp \
		qrc_recordimg.cpp
OBJECTS       = main.o \
		mainwidget.o \
		onescreen.o \
		fourscreen.o \
		button_localvedio_listwidget.o \
		localVedioMenu.o \
		screenModeMenu.o \
		pushButtonMenu.o \
		twoScreen.o \
		nineScreen.o \
		sixteenScreen.o \
		electronicMap.o \
		interactionManager.o \
		vedioMeeting.o \
		vedioSearch.o \
		dateTimeButton.o \
		date.o \
		mediaplayer.o \
		moc_mainwidget.o \
		moc_onescreen.o \
		moc_fourscreen.o \
		moc_button_localvedio_listwidget.o \
		moc_localVedioMenu.o \
		moc_screenModeMenu.o \
		moc_twoScreen.o \
		moc_nineScreen.o \
		moc_sixteenScreen.o \
		moc_electronicMap.o \
		moc_interactionManager.o \
		moc_vedioMeeting.o \
		moc_vedioSearch.o \
		moc_dateTimeButton.o \
		moc_date.o \
		moc_mediaplayer.o \
		qrc_statuslog.o \
		qrc_datetimeimg.o \
		qrc_recordimg.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		zkCar.pro
QMAKE_TARGET  = zkCar
DESTDIR       = 
TARGET        = zkCar

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): /home/tys/software/zkCar/lib/faac/lib/libfaac.a /home/tys/software/zkCar/lib/faad/lib/libfaad.a UI/ui_mainwidget.h UI/ui_onescreen.h UI/ui_fourscreen.h UI/ui_twoscreen.h UI/ui_ninescreen.h UI/ui_sixteenscreen.h UI/ui_electronicmap.h UI/ui_interactionmanager.h UI/ui_vediomeeting.h UI/ui_vediosearch.h UI/ui_mediaplayer.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: zkCar.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtScript.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile zkCar.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtScript.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile zkCar.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/zkCar1.0.0 || $(MKDIR) .tmp/zkCar1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/zkCar1.0.0/ && $(COPY_FILE) --parents mainwidget.h onescreen.h fourscreen.h window_common.h button_localvedio_listwidget.h nofocusrectstyle.h localVedioMenu.h screenModeMenu.h pushButtonMenu.h windowdefine.h zkCarDevEnginge.h zkdevdefine.h twoScreen.h nineScreen.h sixteenScreen.h electronicMap.h interactionManager.h vedioMeeting.h vedioSearch.h dateTimeButton.h date.h mediaplayer.h .tmp/zkCar1.0.0/ && $(COPY_FILE) --parents statuslog.qrc datetimeimg.qrc recordimg.qrc .tmp/zkCar1.0.0/ && $(COPY_FILE) --parents main.cpp mainwidget.cpp onescreen.cpp fourscreen.cpp button_localvedio_listwidget.cpp localVedioMenu.cpp screenModeMenu.cpp pushButtonMenu.cpp twoScreen.cpp nineScreen.cpp sixteenScreen.cpp electronicMap.cpp interactionManager.cpp vedioMeeting.cpp vedioSearch.cpp dateTimeButton.cpp date.cpp mediaplayer.cpp .tmp/zkCar1.0.0/ && $(COPY_FILE) --parents mainwidget.ui onescreen.ui fourscreen.ui twoscreen.ui ninescreen.ui sixteenscreen.ui electronicmap.ui interactionmanager.ui vediomeeting.ui vediosearch.ui mediaplayer.ui .tmp/zkCar1.0.0/ && (cd `dirname .tmp/zkCar1.0.0` && $(TAR) zkCar1.0.0.tar zkCar1.0.0 && $(COMPRESS) zkCar1.0.0.tar) && $(MOVE) `dirname .tmp/zkCar1.0.0`/zkCar1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/zkCar1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwidget.cpp moc_onescreen.cpp moc_fourscreen.cpp moc_button_localvedio_listwidget.cpp moc_localVedioMenu.cpp moc_screenModeMenu.cpp moc_twoScreen.cpp moc_nineScreen.cpp moc_sixteenScreen.cpp moc_electronicMap.cpp moc_interactionManager.cpp moc_vedioMeeting.cpp moc_vedioSearch.cpp moc_dateTimeButton.cpp moc_date.cpp moc_mediaplayer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwidget.cpp moc_onescreen.cpp moc_fourscreen.cpp moc_button_localvedio_listwidget.cpp moc_localVedioMenu.cpp moc_screenModeMenu.cpp moc_twoScreen.cpp moc_nineScreen.cpp moc_sixteenScreen.cpp moc_electronicMap.cpp moc_interactionManager.cpp moc_vedioMeeting.cpp moc_vedioSearch.cpp moc_dateTimeButton.cpp moc_date.cpp moc_mediaplayer.cpp
moc_mainwidget.cpp: window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h \
		onescreen.h \
		UI/ui_onescreen.h \
		twoScreen.h \
		UI/ui_twoscreen.h \
		fourscreen.h \
		UI/ui_fourscreen.h \
		nineScreen.h \
		UI/ui_ninescreen.h \
		sixteenScreen.h \
		UI/ui_sixteenscreen.h \
		localVedioMenu.h \
		pushButtonMenu.h \
		screenModeMenu.h \
		mainwidget.h \
		interactionManager.h \
		UI/ui_interactionmanager.h \
		vedioMeeting.h \
		UI/ui_vediomeeting.h \
		electronicMap.h \
		UI/ui_electronicmap.h \
		vedioSearch.h \
		UI/ui_vediosearch.h \
		dateTimeButton.h \
		mediaplayer.h \
		UI/ui_mediaplayer.h \
		mainwidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwidget.h -o moc_mainwidget.cpp

moc_onescreen.cpp: UI/ui_onescreen.h \
		window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h \
		onescreen.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) onescreen.h -o moc_onescreen.cpp

moc_fourscreen.cpp: UI/ui_fourscreen.h \
		window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h \
		fourscreen.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) fourscreen.h -o moc_fourscreen.cpp

moc_button_localvedio_listwidget.cpp: window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h \
		button_localvedio_listwidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) button_localvedio_listwidget.h -o moc_button_localvedio_listwidget.cpp

moc_localVedioMenu.cpp: window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h \
		pushButtonMenu.h \
		screenModeMenu.h \
		mainwidget.h \
		onescreen.h \
		UI/ui_onescreen.h \
		twoScreen.h \
		UI/ui_twoscreen.h \
		fourscreen.h \
		UI/ui_fourscreen.h \
		nineScreen.h \
		UI/ui_ninescreen.h \
		sixteenScreen.h \
		UI/ui_sixteenscreen.h \
		localVedioMenu.h \
		interactionManager.h \
		UI/ui_interactionmanager.h \
		vedioMeeting.h \
		UI/ui_vediomeeting.h \
		electronicMap.h \
		UI/ui_electronicmap.h \
		vedioSearch.h \
		UI/ui_vediosearch.h \
		dateTimeButton.h \
		mediaplayer.h \
		UI/ui_mediaplayer.h \
		localVedioMenu.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) localVedioMenu.h -o moc_localVedioMenu.cpp

moc_screenModeMenu.cpp: window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h \
		mainwidget.h \
		onescreen.h \
		UI/ui_onescreen.h \
		twoScreen.h \
		UI/ui_twoscreen.h \
		fourscreen.h \
		UI/ui_fourscreen.h \
		nineScreen.h \
		UI/ui_ninescreen.h \
		sixteenScreen.h \
		UI/ui_sixteenscreen.h \
		localVedioMenu.h \
		pushButtonMenu.h \
		screenModeMenu.h \
		interactionManager.h \
		UI/ui_interactionmanager.h \
		vedioMeeting.h \
		UI/ui_vediomeeting.h \
		electronicMap.h \
		UI/ui_electronicmap.h \
		vedioSearch.h \
		UI/ui_vediosearch.h \
		dateTimeButton.h \
		mediaplayer.h \
		UI/ui_mediaplayer.h \
		screenModeMenu.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) screenModeMenu.h -o moc_screenModeMenu.cpp

moc_twoScreen.cpp: UI/ui_twoscreen.h \
		twoScreen.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) twoScreen.h -o moc_twoScreen.cpp

moc_nineScreen.cpp: UI/ui_ninescreen.h \
		nineScreen.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) nineScreen.h -o moc_nineScreen.cpp

moc_sixteenScreen.cpp: UI/ui_sixteenscreen.h \
		sixteenScreen.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sixteenScreen.h -o moc_sixteenScreen.cpp

moc_electronicMap.cpp: UI/ui_electronicmap.h \
		window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h \
		electronicMap.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) electronicMap.h -o moc_electronicMap.cpp

moc_interactionManager.cpp: UI/ui_interactionmanager.h \
		window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h \
		interactionManager.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) interactionManager.h -o moc_interactionManager.cpp

moc_vedioMeeting.cpp: UI/ui_vediomeeting.h \
		vedioMeeting.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) vedioMeeting.h -o moc_vedioMeeting.cpp

moc_vedioSearch.cpp: UI/ui_vediosearch.h \
		dateTimeButton.h \
		window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h \
		mediaplayer.h \
		UI/ui_mediaplayer.h \
		vedioSearch.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) vedioSearch.h -o moc_vedioSearch.cpp

moc_dateTimeButton.cpp: dateTimeButton.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) dateTimeButton.h -o moc_dateTimeButton.cpp

moc_date.cpp: date.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) date.h -o moc_date.cpp

moc_mediaplayer.cpp: UI/ui_mediaplayer.h \
		window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h \
		mediaplayer.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mediaplayer.h -o moc_mediaplayer.cpp

compiler_rcc_make_all: qrc_statuslog.cpp qrc_datetimeimg.cpp qrc_recordimg.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_statuslog.cpp qrc_datetimeimg.cpp qrc_recordimg.cpp
qrc_statuslog.cpp: statuslog.qrc \
		resource/icon/对讲（未选中）.png \
		resource/icon/四分屏.png \
		resource/icon/互动对讲选中.png \
		resource/icon/电量.png \
		resource/icon/对讲（选中）.png \
		resource/icon/logo.png \
		resource/icon/群组对讲（选中）.png \
		resource/icon/对讲菜单（未选中）.png \
		resource/icon/退出会议（未选中）.png \
		resource/icon/退出会议（选中）.png \
		resource/icon/九分屏.png \
		resource/icon/一分屏.png \
		resource/icon/十六分屏.png \
		resource/icon/进入会议（未选中）.png \
		resource/icon/退出（选中）.png \
		resource/icon/头像.png \
		resource/icon/信号.png \
		resource/icon/二分屏.png \
		resource/icon/退出（未选中）.png \
		resource/icon/进入会议（选中）.png \
		resource/icon/位置.png
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name statuslog statuslog.qrc -o qrc_statuslog.cpp

qrc_datetimeimg.cpp: datetimeimg.qrc \
		resource/dateTimeImg/bk.png \
		resource/dateTimeImg/DTNext.png \
		resource/dateTimeImg/DTPrev.png \
		resource/dateTimeImg/ComboBoxArrow.png
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name datetimeimg datetimeimg.qrc -o qrc_datetimeimg.cpp

qrc_recordimg.cpp: recordimg.qrc \
		resource/recordImg/日历（选中）.png \
		resource/recordImg/进度球.png \
		resource/recordImg/播放（选中）.png \
		resource/recordImg/查询（未选中）.png \
		resource/recordImg/日历.png \
		resource/recordImg/暂停.png \
		resource/recordImg/播放.png \
		resource/recordImg/暂停（选中）.png \
		resource/recordImg/查询（选中）.png \
		resource/recordImg/下拉.png \
		resource/recordImg/全屏.png \
		resource/recordImg/下载（选中）拷贝2.png \
		resource/recordImg/全屏（选中）.png
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name recordimg recordimg.qrc -o qrc_recordimg.cpp

compiler_image_collection_make_all: UI/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) UI/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: UI/ui_mainwidget.h UI/ui_onescreen.h UI/ui_fourscreen.h UI/ui_twoscreen.h UI/ui_ninescreen.h UI/ui_sixteenscreen.h UI/ui_electronicmap.h UI/ui_interactionmanager.h UI/ui_vediomeeting.h UI/ui_vediosearch.h UI/ui_mediaplayer.h
compiler_uic_clean:
	-$(DEL_FILE) UI/ui_mainwidget.h UI/ui_onescreen.h UI/ui_fourscreen.h UI/ui_twoscreen.h UI/ui_ninescreen.h UI/ui_sixteenscreen.h UI/ui_electronicmap.h UI/ui_interactionmanager.h UI/ui_vediomeeting.h UI/ui_vediosearch.h UI/ui_mediaplayer.h
UI/ui_mainwidget.h: mainwidget.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainwidget.ui -o UI/ui_mainwidget.h

UI/ui_onescreen.h: onescreen.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic onescreen.ui -o UI/ui_onescreen.h

UI/ui_fourscreen.h: fourscreen.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic fourscreen.ui -o UI/ui_fourscreen.h

UI/ui_twoscreen.h: twoscreen.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic twoscreen.ui -o UI/ui_twoscreen.h

UI/ui_ninescreen.h: ninescreen.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic ninescreen.ui -o UI/ui_ninescreen.h

UI/ui_sixteenscreen.h: sixteenscreen.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic sixteenscreen.ui -o UI/ui_sixteenscreen.h

UI/ui_electronicmap.h: electronicmap.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic electronicmap.ui -o UI/ui_electronicmap.h

UI/ui_interactionmanager.h: interactionmanager.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic interactionmanager.ui -o UI/ui_interactionmanager.h

UI/ui_vediomeeting.h: vediomeeting.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic vediomeeting.ui -o UI/ui_vediomeeting.h

UI/ui_vediosearch.h: vediosearch.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic vediosearch.ui -o UI/ui_vediosearch.h

UI/ui_mediaplayer.h: mediaplayer.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mediaplayer.ui -o UI/ui_mediaplayer.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwidget.h \
		window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h \
		onescreen.h \
		UI/ui_onescreen.h \
		twoScreen.h \
		UI/ui_twoscreen.h \
		fourscreen.h \
		UI/ui_fourscreen.h \
		nineScreen.h \
		UI/ui_ninescreen.h \
		sixteenScreen.h \
		UI/ui_sixteenscreen.h \
		localVedioMenu.h \
		pushButtonMenu.h \
		screenModeMenu.h \
		interactionManager.h \
		UI/ui_interactionmanager.h \
		vedioMeeting.h \
		UI/ui_vediomeeting.h \
		electronicMap.h \
		UI/ui_electronicmap.h \
		vedioSearch.h \
		UI/ui_vediosearch.h \
		dateTimeButton.h \
		mediaplayer.h \
		UI/ui_mediaplayer.h \
		nofocusrectstyle.h \
		zkCarDevEnginge.h \
		zkdevdefine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwidget.o: mainwidget.cpp mainwidget.h \
		window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h \
		onescreen.h \
		UI/ui_onescreen.h \
		twoScreen.h \
		UI/ui_twoscreen.h \
		fourscreen.h \
		UI/ui_fourscreen.h \
		nineScreen.h \
		UI/ui_ninescreen.h \
		sixteenScreen.h \
		UI/ui_sixteenscreen.h \
		localVedioMenu.h \
		pushButtonMenu.h \
		screenModeMenu.h \
		interactionManager.h \
		UI/ui_interactionmanager.h \
		vedioMeeting.h \
		UI/ui_vediomeeting.h \
		electronicMap.h \
		UI/ui_electronicmap.h \
		vedioSearch.h \
		UI/ui_vediosearch.h \
		dateTimeButton.h \
		mediaplayer.h \
		UI/ui_mediaplayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwidget.o mainwidget.cpp

onescreen.o: onescreen.cpp onescreen.h \
		UI/ui_onescreen.h \
		window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o onescreen.o onescreen.cpp

fourscreen.o: fourscreen.cpp fourscreen.h \
		UI/ui_fourscreen.h \
		window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fourscreen.o fourscreen.cpp

button_localvedio_listwidget.o: button_localvedio_listwidget.cpp button_localvedio_listwidget.h \
		window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o button_localvedio_listwidget.o button_localvedio_listwidget.cpp

localVedioMenu.o: localVedioMenu.cpp localVedioMenu.h \
		window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h \
		pushButtonMenu.h \
		screenModeMenu.h \
		mainwidget.h \
		onescreen.h \
		UI/ui_onescreen.h \
		twoScreen.h \
		UI/ui_twoscreen.h \
		fourscreen.h \
		UI/ui_fourscreen.h \
		nineScreen.h \
		UI/ui_ninescreen.h \
		sixteenScreen.h \
		UI/ui_sixteenscreen.h \
		interactionManager.h \
		UI/ui_interactionmanager.h \
		vedioMeeting.h \
		UI/ui_vediomeeting.h \
		electronicMap.h \
		UI/ui_electronicmap.h \
		vedioSearch.h \
		UI/ui_vediosearch.h \
		dateTimeButton.h \
		mediaplayer.h \
		UI/ui_mediaplayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o localVedioMenu.o localVedioMenu.cpp

screenModeMenu.o: screenModeMenu.cpp screenModeMenu.h \
		window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h \
		mainwidget.h \
		onescreen.h \
		UI/ui_onescreen.h \
		twoScreen.h \
		UI/ui_twoscreen.h \
		fourscreen.h \
		UI/ui_fourscreen.h \
		nineScreen.h \
		UI/ui_ninescreen.h \
		sixteenScreen.h \
		UI/ui_sixteenscreen.h \
		localVedioMenu.h \
		pushButtonMenu.h \
		interactionManager.h \
		UI/ui_interactionmanager.h \
		vedioMeeting.h \
		UI/ui_vediomeeting.h \
		electronicMap.h \
		UI/ui_electronicmap.h \
		vedioSearch.h \
		UI/ui_vediosearch.h \
		dateTimeButton.h \
		mediaplayer.h \
		UI/ui_mediaplayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o screenModeMenu.o screenModeMenu.cpp

pushButtonMenu.o: pushButtonMenu.cpp pushButtonMenu.h \
		window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pushButtonMenu.o pushButtonMenu.cpp

twoScreen.o: twoScreen.cpp twoScreen.h \
		UI/ui_twoscreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o twoScreen.o twoScreen.cpp

nineScreen.o: nineScreen.cpp nineScreen.h \
		UI/ui_ninescreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nineScreen.o nineScreen.cpp

sixteenScreen.o: sixteenScreen.cpp sixteenScreen.h \
		UI/ui_sixteenscreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sixteenScreen.o sixteenScreen.cpp

electronicMap.o: electronicMap.cpp electronicMap.h \
		UI/ui_electronicmap.h \
		window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o electronicMap.o electronicMap.cpp

interactionManager.o: interactionManager.cpp interactionManager.h \
		UI/ui_interactionmanager.h \
		window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interactionManager.o interactionManager.cpp

vedioMeeting.o: vedioMeeting.cpp vedioMeeting.h \
		UI/ui_vediomeeting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vedioMeeting.o vedioMeeting.cpp

vedioSearch.o: vedioSearch.cpp vedioSearch.h \
		UI/ui_vediosearch.h \
		dateTimeButton.h \
		window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h \
		mediaplayer.h \
		UI/ui_mediaplayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vedioSearch.o vedioSearch.cpp

dateTimeButton.o: dateTimeButton.cpp dateTimeButton.h \
		date.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dateTimeButton.o dateTimeButton.cpp

date.o: date.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o date.o date.cpp

mediaplayer.o: mediaplayer.cpp mediaplayer.h \
		UI/ui_mediaplayer.h \
		window_common.h \
		UI/ui_mainwidget.h \
		windowdefine.h \
		../hisi3531aLib/zkdevdefine.h \
		../hisi3531aLib/zkCarDevEnginge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mediaplayer.o mediaplayer.cpp

moc_mainwidget.o: moc_mainwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwidget.o moc_mainwidget.cpp

moc_onescreen.o: moc_onescreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_onescreen.o moc_onescreen.cpp

moc_fourscreen.o: moc_fourscreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fourscreen.o moc_fourscreen.cpp

moc_button_localvedio_listwidget.o: moc_button_localvedio_listwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_button_localvedio_listwidget.o moc_button_localvedio_listwidget.cpp

moc_localVedioMenu.o: moc_localVedioMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_localVedioMenu.o moc_localVedioMenu.cpp

moc_screenModeMenu.o: moc_screenModeMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_screenModeMenu.o moc_screenModeMenu.cpp

moc_twoScreen.o: moc_twoScreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_twoScreen.o moc_twoScreen.cpp

moc_nineScreen.o: moc_nineScreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nineScreen.o moc_nineScreen.cpp

moc_sixteenScreen.o: moc_sixteenScreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sixteenScreen.o moc_sixteenScreen.cpp

moc_electronicMap.o: moc_electronicMap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_electronicMap.o moc_electronicMap.cpp

moc_interactionManager.o: moc_interactionManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_interactionManager.o moc_interactionManager.cpp

moc_vedioMeeting.o: moc_vedioMeeting.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_vedioMeeting.o moc_vedioMeeting.cpp

moc_vedioSearch.o: moc_vedioSearch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_vedioSearch.o moc_vedioSearch.cpp

moc_dateTimeButton.o: moc_dateTimeButton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dateTimeButton.o moc_dateTimeButton.cpp

moc_date.o: moc_date.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_date.o moc_date.cpp

moc_mediaplayer.o: moc_mediaplayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mediaplayer.o moc_mediaplayer.cpp

qrc_statuslog.o: qrc_statuslog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_statuslog.o qrc_statuslog.cpp

qrc_datetimeimg.o: qrc_datetimeimg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_datetimeimg.o qrc_datetimeimg.cpp

qrc_recordimg.o: qrc_recordimg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_recordimg.o qrc_recordimg.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

